name: MDE Complaints Monitoring

on:
  push:
    push:
  schedule:
    - cron: '0 20 * * *'

jobs:
  check-complaints:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run script
      run: python bot.py 
      env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
