name: mde complaint checker

on:
  push:
    push:
  schedule:
    - cron: '0 20 * * *'

jobs:
  check-complaints:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run script
      run: python bot.py 
      env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          
    - name: Commit changes
      run: |
        git config --global user.email "amandavhernan@gmail.com"
        git config --global user.name "amandavhernan"
        git add -A
        echo "files added to git staging area"
        git commit -m 'new complaints found' || echo "no changes"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/amandavhernan/enviro_complaints.git || echo "no changes to commit"
        echo "commit successful"
